swagger: "2.0"

host: localhost:10010
# basePath prefixes all resource paths
basePath: /
info:
  $ref: ./info/index.yaml
# during dev, should point to your local machine

schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - multipart/form-data
# format of the responses to the client (Accepts)
produces:
  - application/json

# Import the security definitions
securityDefinitions:
  GlobalSecurity:
    type: apiKey
    in: header
    name: api_key
security:
  - GlobalSecurity: []

paths:
  $ref: ./paths/index.yaml

# complex objects have schema definitions
definitions:
  $ref: ./definitions/index.yaml
